site_name: Projeto Microserviços Insper
site_description: Documentação dos componentes do projeto
site_author: Gioavnny Russo
repo_url: https://github.com/giovannyjvr/plataformas
theme:
  name: material
  palette:
    primary: teal
    accent: amber

nav:
  - Home: index.md
  - Exercícios:
    - Visão geral: exercises.md
    - Exercicio 1: exe1.md
    - Exercicio 2: exe2.md
    - Exercicio 3: exe3.md
    - Exercicio 4: exe4.md
    - Exercicio 5: exe5.md
  - Projeto:
    - Status do Projeto: projeto.md
    - Plano de Custos: Plano-de-custos.md
plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
