pipeline {
  agent any
  environment {
    SERVICE = 'exercise2-auth-service'
    NAME = "yourdockerhubusername/${SERVICE}"
    DOCKER_CREDENTIALS = 'dockerhub-credentials'
    USERNAME = 'yourdockerhubusername'
    TOKEN = 'TOKEN'
  }
  stages {
    stage('Dependencies') {
      steps {
        sh 'mvn clean package'
      }
      post {
        always {
          junit '**/target/surefire-reports/*.xml'
        }
      }
    }
    stage('Build') {
      steps {
        sh 'mvn -B -DskipTests clean package'
      }
    }
    stage('Build & Push Image') {
      steps {
        withCredentials([usernamePassword(credentialsId: "${DOCKER_CREDENTIALS}", usernameVariable: 'USER', passwordVariable: 'PASS')]) {
          sh "docker login -u ${USERNAME} -p ${PASS}"
          sh "docker build -t ${USERNAME}/${SERVICE}:latest ./"
          sh "docker push ${USERNAME}/${SERVICE}:latest"
        }
      }
    }
    stage('Deploy in K8s') {
      steps {
        echo "Placeholder for Kubernetes deployment for ${SERVICE}"
      }
    }
  }
}
