apiVersion: batch/v1
kind: Job
metadata:
  name: k6-loadtest
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: k6
        image: grafana/k6:latest
        args:
          - run
          - /scripts/loadtest.js
        volumeMounts:
          - name: script
            mountPath: /scripts
      volumes:
        - name: script
          configMap:
            name: k6-script
