# k8s/auth-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: 767397705738.dkr.ecr.sa-east-1.amazonaws.com/plataforma-auth-service:latest
          ports:
            - containerPort: 8080
          # se precisar de variáveis de ambiente:
          # env:
          #   - name: SPRING_PROFILES_ACTIVE
          #     value: production
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: auth
