apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchange
  labels:
    app: exchange
spec:
  replicas: 2
  selector:
    matchLabels:
      app: exchange
  template:
    metadata:
      labels:
        app: exchange
    spec:
      containers:
      - name: exchange
        image: docker.io/giovannyjvr/plataforma-exchange-service:latest
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: exchange-service
spec:
  type: ClusterIP
  selector:
    app: exchange
  ports:
  - name: http
    port: 8000
    targetPort: 8000
