# k8s/product.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  labels:
    app: product
spec:
  replicas: 1                            # start pequeno, deixe o HPA escalar
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: 767397705738.dkr.ecr.sa-east-1.amazonaws.com/plataforma-product-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"              # mínimo de CPU para o pod
              memory: "200Mi"          # mínimo de memória
            limits:
              cpu: "200m"              # máximo de CPU
              memory: "300Mi"          # máximo de memória

---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  labels:
    app: product
spec:
  type: LoadBalancer
  selector:
    app: product
  ports:
    - name: http
      port: 8080
      targetPort: 8080
