pipeline {
  agent any
  stages {
    stage('Run services pipelines') {
      steps {
        script {
          def services = ['exercise2-auth-service', 'exercise3-order-service']
          for (svc in services) {
            dir(svc) {
              echo "Loading pipeline for ${svc}"
              load 'Jenkinsfile'
            }
          }
        }
      }
    }
  }
}
